{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "fa459285-fd8a-4fea-98e1-40c6afda8df5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "=== NHẬP THÔNG TIN NGƯỜI DÙNG ===\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Trường học:  FTU\n",
      "Ngân sách tối đa:  3526542\n",
      "Giờ ngủ (vd 23.5):  1\n",
      "Hướng nội(0) / Hướng ngoại(1):  1\n",
      "Nuôi thú cưng? Không(0) / Có(1):  1\n",
      "Mức độ sạch sẽ (1–10):  8\n",
      "Vĩ độ:  21.019312\n",
      "Kinh độ:  105.831687\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== NHẬP TRỌNG SỐ ƯU TIÊN ===\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Ưu tiên cùng trường:  10\n",
      "Ưu tiên giá rẻ:  1\n",
      "Ưu tiên giờ ngủ:  1\n",
      "Ưu tiên sạch sẽ:  1\n",
      "Ưu tiên tính cách:  1\n",
      "Ưu tiên thú cưng:  1\n",
      "\n",
      "Khoảng cách tối đa chấp nhận (km):  5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "=== SINH VIÊN PHÙ HỢP NHẤT ===\n",
      "Student_23 | weight=11.0208 | distance=3.75 km\n",
      "Student_6 | weight=11.0333 | distance=0.0 km\n",
      "Student_96 | weight=11.0833 | distance=4.95 km\n",
      "Student_37 | weight=11.1 | distance=1.07 km\n",
      "Student_29 | weight=11.1046 | distance=2.92 km\n"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "import math\n",
    "\n",
    "# =========================\n",
    "# HÀM CHUẨN HÓA\n",
    "# =========================\n",
    "def norm_diff(a, b, max_val):\n",
    "    \"\"\"\n",
    "    Chuẩn hóa độ chênh lệch về [0,1]\n",
    "    \"\"\"\n",
    "    return abs(a - b) / max_val if max_val != 0 else 0\n",
    "\n",
    "\n",
    "def binary_diff(a, b):\n",
    "    \"\"\"\n",
    "    So sánh tiêu chí nhị phân (giống = 0, khác = 1)\n",
    "    \"\"\"\n",
    "    return 0 if a == b else 1\n",
    "\n",
    "\n",
    "# =========================\n",
    "# TÍNH KHOẢNG CÁCH ĐỊA LÝ\n",
    "# =========================\n",
    "def haversine(lat1, lon1, lat2, lon2):\n",
    "    R = 6371  # km\n",
    "    lat1, lon1, lat2, lon2 = map(math.radians,\n",
    "                                 [lat1, lon1, lat2, lon2])\n",
    "\n",
    "    dlat = lat2 - lat1\n",
    "    dlon = lon2 - lon1\n",
    "\n",
    "    a = (math.sin(dlat / 2) ** 2 +\n",
    "         math.cos(lat1) * math.cos(lat2) *\n",
    "         math.sin(dlon / 2) ** 2)\n",
    "\n",
    "    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))\n",
    "    return R * c\n",
    "\n",
    "\n",
    "# =========================\n",
    "# LOAD CSV\n",
    "# =========================\n",
    "# def load_students(csv_path):\n",
    "#     students = []\n",
    "#     with open(csv_path, newline='', encoding='utf-8') as f:\n",
    "#         reader = csv.DictReader(f)\n",
    "#         for row in reader:\n",
    "#             students.append({\n",
    "#                 \"id\": row[\"ID\"],\n",
    "#                 \"name\": row[\"Name\"],\n",
    "#                 \"school\": row[\"School\"],\n",
    "#                 \"budget\": float(row[\"Budget\"]),\n",
    "#                 \"sleep\": float(row[\"Sleep_Time\"]),\n",
    "#                 \"personality\": int(row[\"Personality\"]),  # 0/1\n",
    "#                 \"pet\": int(row[\"Pet\"]),                  # 0/1\n",
    "#                 \"clean\": float(row[\"Cleanliness\"]),      # 1–10\n",
    "#                 \"lat\": float(row[\"Latitude\"]),\n",
    "#                 \"lon\": float(row[\"Longitude\"])\n",
    "#             })\n",
    "#     return students\n",
    "def load_students(csv_path):\n",
    "    students = []\n",
    "    with open(csv_path, newline='', encoding='utf-8') as f:\n",
    "        reader = csv.DictReader(f)\n",
    "        for row in reader:\n",
    "            students.append({\n",
    "                \"id\": row[\"ID\"],\n",
    "                \"name\": row[\"Name\"],\n",
    "                \"school\": row[\"School_Full_Name\"],   # ← sửa\n",
    "                \"budget\": float(row[\"Budget\"]),\n",
    "                \"sleep\": float(row[\"Sleep_Time\"]),  # ← sửa\n",
    "                \"personality\": int(row[\"Personality\"]),\n",
    "                \"pet\": int(row[\"Pet\"]),\n",
    "                \"clean\": float(row[\"Cleanliness\"]),\n",
    "                \"lat\": float(row[\"Latitude\"]),\n",
    "                \"lon\": float(row[\"Longitude\"])\n",
    "            })\n",
    "    return students\n",
    "\n",
    "\n",
    "# =========================\n",
    "# TÍNH WEIGHT (ĐỘ KHÔNG PHÙ HỢP)\n",
    "# =========================\n",
    "def calculate_weight(user, s, alpha,\n",
    "                     max_budget, max_sleep, max_clean):\n",
    "\n",
    "    weight = 0\n",
    "\n",
    "    # Trường học\n",
    "    weight += alpha[\"school\"] * binary_diff(user[\"school\"], s[\"school\"])\n",
    "\n",
    "    # Budget (phòng rẻ hơn budget → không bị phạt)\n",
    "    if s[\"budget\"] <= user[\"budget\"]:\n",
    "        budget_diff = 0\n",
    "    else:\n",
    "        budget_diff = norm_diff(s[\"budget\"], user[\"budget\"], max_budget)\n",
    "\n",
    "    weight += alpha[\"budget\"] * budget_diff\n",
    "\n",
    "    # Giờ ngủ\n",
    "    weight += alpha[\"sleep\"] * norm_diff(user[\"sleep\"], s[\"sleep\"], max_sleep)\n",
    "\n",
    "    # Độ sạch sẽ\n",
    "    weight += alpha[\"clean\"] * norm_diff(user[\"clean\"], s[\"clean\"], max_clean)\n",
    "\n",
    "    # Tính cách\n",
    "    weight += alpha[\"personality\"] * binary_diff(\n",
    "        user[\"personality\"], s[\"personality\"]\n",
    "    )\n",
    "\n",
    "    # Nuôi thú cưng\n",
    "    weight += alpha[\"pet\"] * binary_diff(user[\"pet\"], s[\"pet\"])\n",
    "\n",
    "    return weight\n",
    "\n",
    "\n",
    "# =========================\n",
    "# RANKING (CÓ HARD DISTANCE)\n",
    "# =========================\n",
    "def rank_students(user, students, alpha, max_distance):\n",
    "    results = []\n",
    "\n",
    "    max_budget = max(s[\"budget\"] for s in students)\n",
    "    max_sleep = 24\n",
    "    max_clean = 10\n",
    "\n",
    "    for s in students:\n",
    "        dist = haversine(\n",
    "            user[\"lat\"], user[\"lon\"],\n",
    "            s[\"lat\"], s[\"lon\"]\n",
    "        )\n",
    "\n",
    "        # HARD DISTANCE CONSTRAINT\n",
    "        if dist > max_distance:\n",
    "            continue\n",
    "\n",
    "        w = calculate_weight(user, s, alpha,\n",
    "                              max_budget, max_sleep, max_clean)\n",
    "\n",
    "        results.append((s, round(w, 4), round(dist, 2)))\n",
    "\n",
    "    results.sort(key=lambda x: x[1])\n",
    "    return results\n",
    "\n",
    "\n",
    "# =========================\n",
    "# MAIN\n",
    "# =========================\n",
    "def main():\n",
    "    print(\"=== NHẬP THÔNG TIN NGƯỜI DÙNG ===\")\n",
    "    user = {\n",
    "        \"school\": input(\"Trường học: \"),\n",
    "        \"budget\": float(input(\"Ngân sách tối đa: \")),\n",
    "        \"sleep\": float(input(\"Giờ ngủ (vd 23.5): \")),\n",
    "        \"personality\": int(input(\"Hướng nội(0) / Hướng ngoại(1): \")),\n",
    "        \"pet\": int(input(\"Nuôi thú cưng? Không(0) / Có(1): \")),\n",
    "        \"clean\": float(input(\"Mức độ sạch sẽ (1–10): \")),\n",
    "        \"lat\": float(input(\"Vĩ độ: \")),\n",
    "        \"lon\": float(input(\"Kinh độ: \"))\n",
    "    }\n",
    "\n",
    "    print(\"\\n=== NHẬP TRỌNG SỐ ƯU TIÊN ===\")\n",
    "    alpha = {\n",
    "        \"school\": float(input(\"Ưu tiên cùng trường: \")),\n",
    "        \"budget\": float(input(\"Ưu tiên giá rẻ: \")),\n",
    "        \"sleep\": float(input(\"Ưu tiên giờ ngủ: \")),\n",
    "        \"clean\": float(input(\"Ưu tiên sạch sẽ: \")),\n",
    "        \"personality\": float(input(\"Ưu tiên tính cách: \")),\n",
    "        \"pet\": float(input(\"Ưu tiên thú cưng: \"))\n",
    "    }\n",
    "\n",
    "    max_distance = float(input(\"\\nKhoảng cách tối đa chấp nhận (km): \"))\n",
    "\n",
    "    students = load_students(\"students_sample.csv\")\n",
    "\n",
    "    ranked = rank_students(user, students, alpha, max_distance)\n",
    "\n",
    "    print(\"\\n=== SINH VIÊN PHÙ HỢP NHẤT ===\")\n",
    "    for s, w, d in ranked[:5]:\n",
    "        print(f\"{s['name']} | weight={w} | distance={d} km\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9f6b27fa-f5ce-4f51-a7d1-d18529d6c8ac",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (499859.py, line 4)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Cell \u001b[1;32mIn[8], line 4\u001b[1;36m\u001b[0m\n\u001b[1;33m    =========================\u001b[0m\n\u001b[1;37m    ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "import csv \n",
    "import math\n",
    "\n",
    "=========================\n",
    "HÀM CHUẨN HÓA\n",
    "=========================\n",
    "def norm_diff(a, b, max_val): \"\"\" Chuẩn hóa độ chênh lệch về [0,1] \"\"\" return abs(a - b) / max_val if max_val != 0 else 0\n",
    "\n",
    "def binary_diff(a, b): \"\"\" So sánh tiêu chí nhị phân (giống = 0, khác = 1) \"\"\" return 0 if a == b else 1\n",
    "\n",
    "=========================\n",
    "TÍNH KHOẢNG CÁCH ĐỊA LÝ\n",
    "=========================\n",
    "def haversine(lat1, lon1, lat2, lon2): R = 6371 # km lat1, lon1, lat2, lon2 = map(math.radians, [lat1, lon1, lat2, lon2])\n",
    "\n",
    "dlat = lat2 - lat1\n",
    "dlon = lon2 - lon1\n",
    "\n",
    "a = (math.sin(dlat / 2) ** 2 +\n",
    "     math.cos(lat1) * math.cos(lat2) *\n",
    "     math.sin(dlon / 2) ** 2)\n",
    "\n",
    "c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))\n",
    "return R * c\n",
    "=========================\n",
    "LOAD CSV\n",
    "=========================\n",
    "def load_students(csv_path):\n",
    "students = []\n",
    "with open(csv_path, newline='', encoding='utf-8') as f:\n",
    "reader = csv.DictReader(f)\n",
    "for row in reader:\n",
    "students.append({\n",
    "\"id\": row[\"ID\"],\n",
    "\"name\": row[\"Name\"],\n",
    "\"school\": row[\"School\"],\n",
    "\"budget\": float(row[\"Budget\"]),\n",
    "\"sleep\": float(row[\"Sleep_Time\"]),\n",
    "\"personality\": int(row[\"Personality\"]), # 0/1\n",
    "\"pet\": int(row[\"Pet\"]), # 0/1\n",
    "\"clean\": float(row[\"Cleanliness\"]), # 1–10\n",
    "\"lat\": float(row[\"Latitude\"]),\n",
    "\"lon\": float(row[\"Longitude\"])\n",
    "})\n",
    "return students\n",
    "def load_students(csv_path): students = [] with open(csv_path, newline='', encoding='utf-8') as f: reader = csv.DictReader(f) for row in reader: students.append({ \"id\": row[\"ID\"], \"name\": row[\"Name\"], \"school\": row[\"School_Full_Name\"], # ← sửa \"budget\": float(row[\"Budget\"]), \"sleep\": float(row[\"Sleep_Time\"]), # ← sửa \"personality\": int(row[\"Personality\"]), \"pet\": int(row[\"Pet\"]), \"clean\": float(row[\"Cleanliness\"]), \"lat\": float(row[\"Latitude\"]), \"lon\": float(row[\"Longitude\"]) }) return students\n",
    "\n",
    "=========================\n",
    "TÍNH WEIGHT (ĐỘ KHÔNG PHÙ HỢP)\n",
    "=========================\n",
    "def calculate_weight(user, s, alpha, max_budget, max_sleep, max_clean):\n",
    "\n",
    "weight = 0\n",
    "\n",
    "# Trường học\n",
    "weight += alpha[\"school\"] * binary_diff(user[\"school\"], s[\"school\"])\n",
    "\n",
    "# Budget (phòng rẻ hơn budget → không bị phạt)\n",
    "if s[\"budget\"] <= user[\"budget\"]:\n",
    "    budget_diff = 0\n",
    "else:\n",
    "    budget_diff = norm_diff(s[\"budget\"], user[\"budget\"], max_budget)\n",
    "\n",
    "weight += alpha[\"budget\"] * budget_diff\n",
    "\n",
    "# Giờ ngủ\n",
    "weight += alpha[\"sleep\"] * norm_diff(user[\"sleep\"], s[\"sleep\"], max_sleep)\n",
    "\n",
    "# Độ sạch sẽ\n",
    "weight += alpha[\"clean\"] * norm_diff(user[\"clean\"], s[\"clean\"], max_clean)\n",
    "\n",
    "# Tính cách\n",
    "weight += alpha[\"personality\"] * binary_diff(\n",
    "    user[\"personality\"], s[\"personality\"]\n",
    ")\n",
    "\n",
    "# Nuôi thú cưng\n",
    "weight += alpha[\"pet\"] * binary_diff(user[\"pet\"], s[\"pet\"])\n",
    "\n",
    "return weight\n",
    "=========================\n",
    "RANKING (CÓ HARD DISTANCE)\n",
    "=========================\n",
    "def rank_students(user, students, alpha, max_distance): results = []\n",
    "\n",
    "max_budget = max(s[\"budget\"] for s in students)\n",
    "max_sleep = 24\n",
    "max_clean = 10\n",
    "\n",
    "for s in students:\n",
    "    dist = haversine(\n",
    "        user[\"lat\"], user[\"lon\"],\n",
    "        s[\"lat\"], s[\"lon\"]\n",
    "    )\n",
    "\n",
    "    # HARD DISTANCE CONSTRAINT\n",
    "    if dist > max_distance:\n",
    "        continue\n",
    "\n",
    "    w = calculate_weight(user, s, alpha,\n",
    "                          max_budget, max_sleep, max_clean)\n",
    "\n",
    "    results.append((s, round(w, 4), round(dist, 2)))\n",
    "\n",
    "results.sort(key=lambda x: x[1])\n",
    "return results\n",
    "=========================\n",
    "MAIN\n",
    "=========================\n",
    "def main(): print(\"=== NHẬP THÔNG TIN NGƯỜI DÙNG ===\") user = { \"school\": input(\"Trường học: \"), \"budget\": float(input(\"Ngân sách tối đa: \")), \"sleep\": float(input(\"Giờ ngủ (vd 23.5): \")), \"personality\": int(input(\"Hướng nội(0) / Hướng ngoại(1): \")), \"pet\": int(input(\"Nuôi thú cưng? Không(0) / Có(1): \")), \"clean\": float(input(\"Mức độ sạch sẽ (1–10): \")), \"lat\": float(input(\"Vĩ độ: \")), \"lon\": float(input(\"Kinh độ: \")) }\n",
    "\n",
    "print(\"\\n=== NHẬP TRỌNG SỐ ƯU TIÊN ===\")\n",
    "alpha = {\n",
    "    \"school\": float(input(\"Ưu tiên cùng trường: \")),\n",
    "    \"budget\": float(input(\"Ưu tiên giá rẻ: \")),\n",
    "    \"sleep\": float(input(\"Ưu tiên giờ ngủ: \")),\n",
    "    \"clean\": float(input(\"Ưu tiên sạch sẽ: \")),\n",
    "    \"personality\": float(input(\"Ưu tiên tính cách: \")),\n",
    "    \"pet\": float(input(\"Ưu tiên thú cưng: \"))\n",
    "}\n",
    "\n",
    "max_distance = float(input(\"\\nKhoảng cách tối đa chấp nhận (km): \"))\n",
    "\n",
    "students = load_students(\"students_sample.csv\")\n",
    "\n",
    "ranked = rank_students(user, students, alpha, max_distance)\n",
    "\n",
    "print(\"\\n=== SINH VIÊN PHÙ HỢP NHẤT ===\")\n",
    "for s, w, d in ranked[:5]:\n",
    "    print(f\"{s['name']} | weight={w} | distance={d} km\")\n",
    "if name == \"main\": main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "67ac2ac0-98ae-4c2a-878c-b5fc09a65289",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
